spring:
  application:
    name: product-service
server:
  port: ${PORT:0}
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    enabled: true #this is enabled by default, just putting out here to remember is true by default and @EnableEurekaClient is no longer necessary
    service-url:
      default-zone: http://localhost:8761/eureka
